#cloud-config
# ==============================================
# Autoinstall Configuration for AI Agent ISO
# ==============================================
# This file is used for Ubuntu autoinstall (subiquity)
# Boot with kernel params: autoinstall ds=nocloud\;s=/cdrom/
# ==============================================

version: 1
interactive-sections: []
locale: en_US
keyboard:
  layout: us
identity:
  hostname: aiagent
  username: aiadmin
  password: "$6$rounds=4096$abcdefg$ZyXwVUT..."  # Replace with hashed password
storage:
  layout:
    name: lvm
packages:
  - git
  - curl
  - docker.io
  - docker-compose
  - python3
  - python3-venv
  - unzip
  - openssh-server
  - nfs-common
  - net-tools
  - dnsmasq
  - pxelinux
  - syslinux
  - grsync
  - rsync
  - jq
  - wget
  - zsh
  - tmux
  - htop
  - neofetch
  - ventoy
  - cloud-init
  - open-iscsi
  - build-essential
  - ubuntu-drivers-common
user-data:
  disable_root: false
  ssh:
    install-server: true
    allow-pw: true
  apt:
    primary:
      - arches: [amd64]
        uri: http://archive.ubuntu.com/ubuntu
late-commands:
  - curtin in-target -- bash -c "cd /home/aiadmin && git clone https://github.com/your-org/ai-agent-stack.git && cd ai-agent-stack && chmod +x *.sh && ./deploy.sh"
  - curtin in-target -- bash -c "echo 'aiadmin ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers"
  - curtin in-target -- systemctl enable docker
  - curtin in-target -- echo 'Installation complete. Ready to boot.' > /home/aiadmin/READY.TXT
write_files:
  - path: /home/aiadmin/README.txt
    content: |
      Welcome to the AI Agent Bootable System.
      The full stack will deploy automatically after install.
  - path: /etc/motd
    content: |
      🧠 AI Agent OS Ready - Enjoy building!
