# .github/workflows/ci.yml
# ==============================================
# GitHub Actions workflow for Kind OS
# ==============================================

name: kOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run unit tests
      run: pytest tests/

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --exclude=web --max-line-length=100

    - name: Package kOS (placeholder)
      run: echo "Packaging logic can be inserted here for ISO or docker build..."

    - name: Upload logs on failure
      if: failure()
      run: |
        mkdir -p logs
        echo "CI failed at $(date)" > logs/ci-failure.log
